#data_source: https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction
data_source: heart-failure.csv
artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv
  
