#data_source: https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction
data_source: heart-failure.csv
artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv
  
  model_dir: model_dir
  model_filename: RandomForest.model

  reports_dir: reports_dir
  scores: scores.json